"""Instância do banco finalizada

Revision ID: 01b20583356e
Revises: 
Create Date: 2020-05-29 10:57:47.187123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01b20583356e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento')
    )
    op.create_table('tipopessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('apartamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartamento_idpredio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartamento_idpredio'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartamento_idpredio')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=12), nullable=False),
    sa.Column('foto', sa.String(length=80), nullable=False),
    sa.Column('tipopessoa', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tipopessoa'], ['tipopessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('foto'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encomenda_idpessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encomenda_idpessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encomenda_idpessoa')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_idapartamento', sa.Integer(), nullable=False),
    sa.Column('entrada_idpredio', sa.Integer(), nullable=False),
    sa.Column('entrada_idpessoa', sa.Integer(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_idapartamento'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['entrada_idpessoa'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['entrada_idpredio'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('entrada_idapartamento'),
    sa.UniqueConstraint('entrada_idpessoa'),
    sa.UniqueConstraint('entrada_idpredio')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.Column('funcionario_idpessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_idpessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_idpessoa'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('senha')
    )
    op.create_table('morador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morador_idapartamento', sa.Integer(), nullable=False),
    sa.Column('morador_idpredio', sa.Integer(), nullable=False),
    sa.Column('morador_idpessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['morador_idapartamento'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['morador_idpessoa'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['morador_idpredio'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('morador_idapartamento'),
    sa.UniqueConstraint('morador_idpessoa'),
    sa.UniqueConstraint('morador_idpredio')
    )
    op.create_table('problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('problema_idpredio', sa.Integer(), nullable=False),
    sa.Column('problema_idapartamento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problema_idapartamento'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['problema_idpredio'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('problema_idapartamento'),
    sa.UniqueConstraint('problema_idpredio')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.Column('evento_idmorador', sa.Integer(), nullable=False),
    sa.Column('evento_idpredio', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_idmorador'], ['morador.id'], ),
    sa.ForeignKeyConstraint(['evento_idpredio'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('evento_idmorador'),
    sa.UniqueConstraint('evento_idpredio')
    )
    op.create_table('saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saida_idpessoa', sa.Integer(), nullable=False),
    sa.Column('saida_identrada', sa.Integer(), nullable=True),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saida_identrada'], ['entrada.id'], ),
    sa.ForeignKeyConstraint(['saida_idpessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('saida_identrada'),
    sa.UniqueConstraint('saida_idpessoa')
    )
    op.create_table('listaconvidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('rg', sa.String(length=12), nullable=False),
    sa.Column('listaconvidados_idevento', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listaconvidados_idevento'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listaconvidados_idevento'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('rg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listaconvidados')
    op.drop_table('saida')
    op.drop_table('evento')
    op.drop_table('problema')
    op.drop_table('morador')
    op.drop_table('funcionario')
    op.drop_table('entrada')
    op.drop_table('encomenda')
    op.drop_table('pessoa')
    op.drop_table('apartamento')
    op.drop_table('tipopessoa')
    op.drop_table('predio')
    # ### end Alembic commands ###
