"""empty message

Revision ID: 0a4a540062e1
Revises: 3812a2d64d41
Create Date: 2020-06-18 15:12:58.656948

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a4a540062e1'
down_revision = '3812a2d64d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('nome', table_name='pessoa')
    op.drop_index('evento', table_name='predio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('evento', 'predio', ['evento'], unique=True)
    op.create_index('nome', 'pessoa', ['nome'], unique=True)
    # ### end Alembic commands ###
