"""empty message

Revision ID: 3812a2d64d41
Revises: 
Create Date: 2020-06-16 16:02:48.742801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3812a2d64d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('predio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evento', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('evento')
    )
    op.create_table('sysaccess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=20), nullable=False),
    sa.Column('senha', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login'),
    sa.UniqueConstraint('senha')
    )
    op.create_table('tipopessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao')
    )
    op.create_table('apartamento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('apartamento_idprd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['apartamento_idprd'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('apartamento_idprd')
    )
    op.create_table('pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('cpf', sa.String(length=14), nullable=False),
    sa.Column('rg', sa.String(length=12), nullable=False),
    sa.Column('foto', sa.String(length=80), nullable=False),
    sa.Column('tp', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tp'], ['tipopessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('foto'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('rg')
    )
    op.create_table('encomenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encomenda_idpes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['encomenda_idpes'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('encomenda_idpes')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entrada_idapt', sa.Integer(), nullable=False),
    sa.Column('entrada_idprd', sa.Integer(), nullable=False),
    sa.Column('entrada_idpes', sa.Integer(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['entrada_idapt'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['entrada_idpes'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['entrada_idprd'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('entrada_idapt'),
    sa.UniqueConstraint('entrada_idpes'),
    sa.UniqueConstraint('entrada_idprd')
    )
    op.create_table('funcionario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('func_idpessoa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['func_idpessoa'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('func_idpessoa')
    )
    op.create_table('morador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('morador_idapt', sa.Integer(), nullable=False),
    sa.Column('morador_idprd', sa.Integer(), nullable=False),
    sa.Column('morador_idpes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['morador_idapt'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['morador_idpes'], ['pessoa.id'], ),
    sa.ForeignKeyConstraint(['morador_idprd'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('morador_idapt'),
    sa.UniqueConstraint('morador_idpes'),
    sa.UniqueConstraint('morador_idprd')
    )
    op.create_table('problema',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(length=200), nullable=False),
    sa.Column('problema_idprd', sa.Integer(), nullable=False),
    sa.Column('problema_idapt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['problema_idapt'], ['apartamento.id'], ),
    sa.ForeignKeyConstraint(['problema_idprd'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('descricao'),
    sa.UniqueConstraint('problema_idapt'),
    sa.UniqueConstraint('problema_idprd')
    )
    op.create_table('evento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.Column('evento_idmrd', sa.Integer(), nullable=False),
    sa.Column('evento_idprd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['evento_idmrd'], ['morador.id'], ),
    sa.ForeignKeyConstraint(['evento_idprd'], ['predio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('evento_idmrd'),
    sa.UniqueConstraint('evento_idprd')
    )
    op.create_table('saida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('saida_idpes', sa.Integer(), nullable=False),
    sa.Column('saida_ident', sa.Integer(), nullable=True),
    sa.Column('datahora', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['saida_ident'], ['entrada.id'], ),
    sa.ForeignKeyConstraint(['saida_idpes'], ['pessoa.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('datahora'),
    sa.UniqueConstraint('saida_ident'),
    sa.UniqueConstraint('saida_idpes')
    )
    op.create_table('listaconvidados',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('rg', sa.String(length=12), nullable=False),
    sa.Column('listaconvidados_idevt', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['listaconvidados_idevt'], ['evento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listaconvidados_idevt'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('rg')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('listaconvidados')
    op.drop_table('saida')
    op.drop_table('evento')
    op.drop_table('problema')
    op.drop_table('morador')
    op.drop_table('funcionario')
    op.drop_table('entrada')
    op.drop_table('encomenda')
    op.drop_table('pessoa')
    op.drop_table('apartamento')
    op.drop_table('tipopessoa')
    op.drop_table('sysaccess')
    op.drop_table('predio')
    # ### end Alembic commands ###
